neo:
    title: Zero
    description: 分享技术，品味生活

spring:
    mvc:
        view:
            prefix: /WEB-INF/JSP/
            suffix: .jsp

    thymeleaf:
        cache: false  # 设置为false   关闭Thymeleaf的缓存，
                      # 不然在开发过程中修改页面不会立刻生效需要重启，生产可配置为 true。
